---
- hosts: 192.168.60.20
  become: yes

  vars:
    node_apps_location: /usr/local/opt/node

  tasks:

    - name: Ensure Node.js app folder exists.
      file: "path={{ node_apps_location }} state=directory"

    - name: Transfer example Node.js app from my mac to server.
      synchronize:
        src: /Users/vagrant/Public/app/app.js
        dest: "{{ node_apps_location }}"
        mode: push
      delegate_to: 192.168.0.30
      
